### PR TITLE
Add GJHttpResult Class Object

### PR DESCRIPTION
**Pull request by CallocGD**
@Wyliemaster So I recently reverse engineered this GJHttpResult object a while ago and I was wondering if you wanted to add it to your repository. I will let you modify anything are there is any spelling mistakes or errors in the code.

### CODE REVIEW

**Comment by SergeyMC9730** [comment]
Nice.

**Review by SergeyMC9730 — APPROVED** [review]

**Comment by SergeyMC9730** [comment]
would be nice if you renamed this pr into like `Add Some GD Classes`

**Comment by SergeyMC9730** [comment]
this is insane bro

**Comment by CallocGD** [comment]
I know it's mostly just a fork I wonder if I should close this PR since it's just 2.2 stuff.

**Comment by CallocGD** [comment]
@SergeyMC9730 I'm gonna close this PR since it's all 2.2 stuff , sorry to disappoint anyone that needed 2.113 stuff. Until Wylie comes back and makes a 2.2 repository.

**Pull request closed without merging**
